name: Tweet latest progress
 
on:
  schedule:
    - cron:  '0 12 * * *'  # 12:00 UTC (vaccination data is typically updated in UK time)

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9.1'
      - name: install dependencies
        run: pip install -r requirements.txt
#       - name: run script
#         env:
#           BOT_API: ${{ secrets.BOT_API }}
#           BOT_API_SECRET: ${{ secrets.BOT_API_SECRET }}
#           BOT_ACCESS: ${{ secrets.BOT_ACCESS }}
#           BOT_ACCESS_SECRET: ${{ secrets.BOT_ACCESS_SECRET }}
#         run: python run.py
      - name: run script
        working-directory: state_data/
        run: python state_vaccinations.py
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          # Optional but recommended
          # Defaults to "Apply automatic changes"
          commit_message: Vaccinations update

          # Optional options appended to `git-commit`
          # See https://git-scm.com/docs/git-commit for a list of available options
          commit_options: '--no-verify --signoff'

          # Optional glob pattern of files which should be added to the commit
          # Defaults to all (.)
          # See the `pathspec`-documentation for git
          # - https://git-scm.com/docs/git-add#Documentation/git-add.txt-ltpathspecgt82308203
          # - https://git-scm.com/docs/gitglossary#Documentation/gitglossary.txt-aiddefpathspecapathspec
          file_pattern: \*.csv

          # Optional local file path to the repository
          # Defaults to the root of the repository
          # repository: state_data

          # Optional commit user and author settings
          commit_user_name: vaccinations-update-bot # defaults to "GitHub Actions"
          # commit_user_email: my-github-actions-bot@example.org # defaults to "actions@github.com"
          # commit_author: Author <actions@github.com> # defaults to author of the commit that triggered the run

          # Optional tag message 
          # Action will create and push a new tag to the remote repository and the defined branch
          # tagging_message: 'v1.0.0'

          # Optional options appended to `git-push`
          # See git-push documentation for details: https://git-scm.com/docs/git-push#_options
          push_options: '--force'

          # Optional: Disable dirty check and always try to create a commit and push
          skip_dirty_check: true    

          # Optional: Skip internal call to `git fetch`
          skip_fetch: true    

          # Optional: Prevents the shell from expanding filenames. Details: https://www.gnu.org/software/bash/manual/html_node/Filename-Expansion.html
          disable_globbing: true
